name: movie_stars
description: "A Flutter app to display popular people from TMDB."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  device_preview: ^1.2.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  go_router: ^16.0.0
  lazy_loading_list: ^1.0.1
  pretty_dio_logger: ^1.4.0
  cached_network_image: ^3.3.1
  saver_gallery: ^4.0.1
  permission_handler: ^12.0.1
#  device_info_plus: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic